import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"
import Footer from "@/components/footer"
import Chat from "@/components/chat"

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ['400', '500', '600', "900"],
  subsets: ['latin'],
  variable: "--poppins",
  display: "swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${inter.className} ${poppins.className}`}>
        <Header />
        {children}
        <Footer />
        <Chat />
      </body>
    </html>
  );
}
