/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/F8FgsL7TiDb
 */
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export default function Chat() {
  return (
    <div className="flex flex-col h-[480px] border border-gray-200 rounded-lg dark:border-gray-800">
      <div className="flex items-center justify-between p-4 border-b dark:border-gray-800">
        <div className="flex items-center space-x-4">
          <div className="font-semibold">Customer Support</div>
          <Badge>Online</Badge>
        </div>
        <Button variant="outline">New chat</Button>
      </div>
      <div className="flex-1 grid p-4 gap-4">
        <div className="flex items-start gap-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="User avatar" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-2">
            <div className="flex items-center space-x-2">
              <div className="font-semibold">John Doe</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">2 minutes ago</div>
            </div>
            <div>Hi there! I'm having trouble with my recent order. Can you help me track it?</div>
          </div>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="User avatar" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-2">
            <div className="flex items-center space-x-2">
              <div className="font-semibold">John Doe</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">2 minutes ago</div>
            </div>
            <div>Hi there! I'm having trouble with my recent order. Can you help me track it?</div>
          </div>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-10 h-10">
            <AvatarImage alt="User avatar" src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
          <div className="flex-1 space-y-2">
            <div className="flex items-center space-x-2">
              <div className="font-semibold">John Doe</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">2 minutes ago</div>
            </div>
            <div>Hi there! I'm having trouble with my recent order. Can you help me track it?</div>
          </div>
        </div>
      </div>
      <div className="flex items-center p-4 border-t">
        <Input className="flex-1 min-h-[40px]" placeholder="Type your message" type="email" />
        <Button className="h-10">Send</Button>
      </div>
    </div>
  )
}
